## 6.1 异常类

Throwable类有两个主要参数：**一个是message，表示异常消息；另一个是cause，表示触发该异常的其他异常**。异常可以形成一个**异常链**，上层的异常由底层异常触发，cause表示底层异常。Throwable还有一个public方法用于设置cause

**Throwable是所有异常的基类**，它有两个子类：`Error`和`Exception`。  
**Error表示系统错误或资源耗尽，由Java系统自己使用，应用程序不应抛出和处理**，比如虚拟机错误（VirtualMacheError）及其子类内存溢出错误（OutOfMemory-Error）和栈溢出错误（StackOverflowError）。  
**Exception表示应用程序错误**，它有很多子类，应用程序也可以通过继承Exception或其子类创建自定义异常

RuntimeException比较特殊，它的名字有点误导，因为其他异常也是运行时产生的，它表示的实际含义是**未受检异常（unchecked exception）**，相对而言，Exception的其他子类和Exception自身则是**受检异常（checked exception）**, Error及其子类也是未受检异常。

**受检（checked）和未受检（unchecked）**的区别在于Java如何处理这两种异常。对于**受检异常，Java会强制要求程序员进行处理(抛出或捕获)，否则会有编译错误**，而对于未受检异常则没有这个要求

## 6.2 异常处理

异常处理机制将根据抛出的异常类型找第一个匹配的`catch块`，找到后，执行catch块内的代码，不再执行其他catch块，如果没有找到，会继续到上层方法中查找。

> 需要注意的是，抛出的异常类型是catch中声明异常的子类也算匹配，所以**需要将最具体的子类放在前面**，如果基类Exception放在前面，则其他更具体的catch代码将得不到执行。

finally语句有一个执行细节，如果在try或者catch语句内有return语句，则return语句在finally语句执行结束后才执行，但finally并不能改变返回值

>  如果在finally中也有return语句呢？try和catch内的return会丢失，实际会返回finally中的返回值。finally中有return不仅会覆盖try和catch内的返回值，还会掩盖try和catch内的异常，就像异常没有发生一样

**关键字throws**，用于**声明一个方法可能抛出的异常**   
throws跟在**方法的括号后面**，可以声明**多个异常**，以逗号分隔。这个声明的含义是，这个方法内可能抛出这些异常，且没有对这些异常进行处理，至少没有处理完，调用者必须进行处理

受检异常必须出现在throws语句中，调用者必须处理，Java编译器会强制这一点，而未受检异常则没有这个要求。

**未受检异常**表示编程的逻辑错误，编程时应该检查以避免这些错误，比如空指针异常，如果真的出现了这些异常，程序退出也是正常的，程序员应该检查程序代码的bug而不是想办法处理这种异常。   
**受检异常**表示程序本身没问题，但由于I/O、网络、数据库等其他不可预测的错误导致的异常，调用者应该进行适当处理。

